services:
  devcontainer:
    build:
      context: ..
      dockerfile: ./Dockerfile
      args:
        UID: ${USER_ID}
        GID: ${GROUP_ID}
    command: sleep infinity
    volumes:
      - ..:/workspace/bookros2_ws/src/book_ros2
      - ${HOST_CLAUDE_DIR}:/home/dev/.claude
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu, graphics, display, compute, utility]
    network_mode: host
