services:
  devcontainer:
    build:
      context: ..
      dockerfile: ./Dockerfile
      args:
        UID: 1000
        GID: 1000
    working_dir: /workspace/bookros2_ws/
    command: sleep infinity
    volumes:
      - ..:/workspace/bookros2_ws/src/book_ros2
      - /workspace/bookros2_ws/build # don't override
      - /workspace/bookros2_ws/install # don't override
      - /workspace/bookros2_ws/log # don't override
      - /home/mateusz/.claude:/home/dev/.claude # to preserve chat history and tokens across container rebuilds
    network_mode: host
